name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
  schedule:
    - cron: 0 0 * * 1
  workflow_dispatch:

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build and push alpine image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: jiting/ruby
          path: .
          dockerfile: 2.7/alpine3.12/Dockerfile
          tags: 2.7.1-alpine,2.7-alpine,alpine
          
      - name: Build and push slim image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: jiting/ruby
          path: /2.7/buster/slim
          dockerfile: Dockerfile
          tags: 2.7.1-slim-buster,2.7-slim-buster,alpine,2.7-slim,slim,latest
