name: Docker

on:
  push:
  schedule:
    - cron: 0 0 * * 1
  workflow_dispatch:

jobs:
  slim:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
          
      - name: Build and push slim image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: jiting/ruby
          path: 2.7/buster/slim
          tags: 2.7.1-slim-buster,2.7-slim-buster,2.7-slim,2.7.1,2.7,slim,latest
  
  alpine:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and push alpine image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: jiting/ruby
          path: 2.7/alpine3.12
          tags: 2.7.1-alpine,2.7-alpine,alpine
