name: Build images

on:
  push:
  pull_request:
  schedule:
    - cron: 0 0 * * 1
  workflow_dispatch:

jobs:  
  slim:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1 
        with:
          username: jiting
          password: ${{ secrets.DOCKER_TOKEN }}
      - 
        name: Build and push slim image

        uses: docker/build-push-action@v2
        with:
          context: 2.7/buster/slim
          file: ./Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            jiting/ruby:2.7.1-slim-buster
            jiting/ruby:2.7-slim-buster
            jiting/ruby:2.7-slim
            jiting/ruby:slim
  buster:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1 
        with:
          username: jiting
          password: ${{ secrets.DOCKER_TOKEN }}
      - 
        name: Build and push slim image

        uses: docker/build-push-action@v2
        with:
          context: 2.7/buster
          file: ./Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            jiting/ruby:2.7.1-buster
            jiting/ruby:2.7-buster
            jiting/ruby:2.7.1
            jiting/ruby:2.7
            jiting/ruby:buster

  alpine:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1 
        with:
          username: jiting
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push alpine image
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v2
        with:
          context: 2.7/alpine3.12
          file: ./Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            jiting/ruby:2.7.1-alpine
            jiting/ruby:2.7-alpine
            jiting/ruby:alpine
            jiting/ruby:latest

  slim-3_0_preview:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1 
        with:
          username: jiting
          password: ${{ secrets.DOCKER_TOKEN }}
      - 
        name: Build and push slim image

        uses: docker/build-push-action@v2
        with:
          context: 3.0/buster/slim
          file: ./Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            jiting/ruby:3.0.0-preview1-slim-buster
            jiting/ruby:3.0.0-preview1-slim
  
  alpine-3_0_preview:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1 
        with:
          username: jiting
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push alpine image
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v2
        with:
          context: 3.0/alpine3.12
          file: ./Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            jiting/ruby:3.0.0-preview1-alpine